run "~/.tmux/plugins/tmux/catppuccin.tmux"

set -g set-clipboard on
set -g default-command "reattach-to-user-namespace -l zsh -d -l"

set -sq escape-time 10

bind p choose-buffer
set -g buffer-limit 100

set-option -g status-position top
set-option -g focus-events on

set -g base-index 1
setw -g mode-keys vi
set -g default-terminal "tmux-256color"

set -g mouse off
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "none"

set -g status-right-length 200
set -g status-left-length 100

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_weather}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -agF status-right "#{E:@catppuccin_status_date_time}"

bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi v send-keys -X begin-selection

unbind-key -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel

bind-key -T prefix & kill-window
bind-key -T prefix x kill-pane


unbind Up     
unbind Down   
unbind Left   
unbind Right  

unbind C-Up   
unbind C-Down 
unbind C-Left 
unbind C-Right

set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'xamut/tmux-weather'
set -g @plugin 'tmux-plugins/tpm'

run '/opt/homebrew/opt/tpm/share/tpm/tpm'
